### ISSUE TITLE
simulating sedimentary basins

### ISSUE THREAD

**Issue by karimnorouzi** [OpenSWPC/OpenSWPC#10]
Thanks a lot for sharing the code. I was wondering how to model a sedimantary basin ?
The examples I noticed dont have hetrogenity in the. May be I have missed something ?

**Comment by karimnorouzi** [comment]
I like to elaborate on my first question. 
I have a DEM for my region, material density and depth to bedrock. How do I go from these data to a mesh that I can use in the program ?

**Comment by tktmyd** [comment]
Please read the entire document, not only the example files. The vmodel='grd' would fit your situation. 
https://tktmyd.github.io/OpenSWPC/English/2._Parameter_Settings/0206_vmodel/
