### ISSUE TITLE
unable to calculate greens functions, getting following error. 

### ISSUE THREAD

**Issue by pa1kumarv** [OpenSWPC/OpenSWPC#13]
If i set 
green_mode       = .true.           
giving following error
assert{0}] failed at m_green.F90(218)
[assert{1}] failed at m_green.F90(218)
[assert{2}] failed at m_green.F90(218)
[assert{3}] failed at m_green.F90(218)

**Comment by tktmyd** [comment]
This assertion error means that process #0-3 ({0}, {1}, {2}, {3}) detected a problem in line 218 of the code `m_green.F90`.

In this particular case, `swpc_3d.x` fails to read four columns (longitude, latitude, depth, ID number) from Green's function list file (`fn_glst`). Maybe the file is available and opened successfully, but its format does not match what was expected. Note that ID numbers must be integers.

**Comment by pa1kumarv** [comment]
Thank you sir for your quick reply. It is working fine now.

Is there any way to generate only greens function? because we want to use those synthetics for 3d moment tensor inversion.

if you able provide some example it will be grateful for our future research.

**Comment by pa1kumarv** [comment]
Sir, can you please give the example for fn_glst  for greens function list?
