### ISSUE TITLE
parallelization

### ISSUE THREAD

**Issue by taborra84** [OpenSWPC/OpenSWPC#16]
I have a 16 core pc but when i run a 2d simulation with this parameters   nproc_x = 4 nproc_y = 4 it use all the 16 core instead of 4

**Comment by tktmyd** [comment]
Hi @taborra84. I suppose the OpenMP uses four threads per one process, leading 16 core usage. Please try the following environmental variable setting before running the 2D code to disable OpenMP: 
```bash
export OMP_NUM_THREADS=1
```

**Comment by taborra84** [comment]
Now it works. Thank you!
