### ISSUE TITLE
errors when compiling the 2d PSV and SH

### ISSUE THREAD

**Issue by gaoyajian** [OpenSWPC/OpenSWPC#2]
When I compiling the 2d-PSV and SH, typing with FC=mpif90, but the 3d code is ok
mpif90     -o m_global.o	  -c m_global.F90
mpif90     -o m_vmodel_uni.o	  -c m_vmodel_uni.F90
mpif90     -o m_bicubic.o	  -c ../shared/m_bicubic.F90
mpif90     -o m_gk.o	  -c ../shared/m_gk.F90
mpif90     -o m_geomap.o	  -c ../shared/m_geomap.F90
mpif90     -o m_vmodel_grd.o	  -c m_vmodel_grd.F90
mpif90     -o m_vmodel_lhm.o	  -c m_vmodel_lhm.F90
mpif90     -o m_rdrmed.o	  -c ../shared/m_rdrmed.F90
mpif90     -o m_vmodel_uni_rmed.o	  -c m_vmodel_uni_rmed.F90
mpif90     -o m_vmodel_lhm_rmed.o	  -c m_vmodel_lhm_rmed.F90
mpif90     -o m_vmodel_grd_rmed.o	  -c m_vmodel_grd_rmed.F90
mpif90     -o m_vmodel_user.o	  -c m_vmodel_user.F90
mpif90     -o m_medium.o	  -c m_medium.F90
mpif90     -o m_kernel.o	  -c m_kernel.F90
mpif90     -o m_getopt.o	  -c ../shared/m_getopt.F90
mpif90     -o m_source.o	  -c m_source.F90
mpif90     -o m_report.o	  -c m_report.F90
mpif90     -o m_wsac.o	  -c ../shared/m_wsac.F90
mpif90     -o m_output.o	  -c m_output.F90
m_output.F90:1295:88:

 ( nf90_open( trim(odir) //'/'// trim(title) //'.xz.ps.nc', NF90_WRITE, xz_ps%io
                                                                     1
Error: Symbol ‘nf90_write’ at (1) has no IMPLICIT type
m_output.F90:800:50:

     call nc_chk( nf90_put_att( hdr%io, NF90_GLOBAL, 'generated_by',   'SWPC' ) 
                                                  1
Error: Symbol ‘nf90_global’ at (1) has no IMPLICIT type
m_output.F90:783:53:

     call nc_chk( nf90_def_var( hdr%io, 'x', NF90_REAL, hdr%did_x1, hdr%vid_x1 )
                                                     1
Error: Symbol ‘nf90_real’ at (1) has no IMPLICIT type
m_output.F90:782:58:

     call nc_chk( nf90_def_dim( hdr%io, 't', NF90_UNLIMITED, hdr%did_t ) )
                                                          1
Error: Symbol ‘nf90_unlimited’ at (1) has no IMPLICIT type
m_output.F90:1324:21:

         call nc_chk( nf90_redef( xz_ps%io ) )
                     1
Error: Function ‘nf90_redef’ at (1) has no IMPLICIT type
m_output.F90:1326:23:

           call nc_chk( nf90_put_att( xz_ps%io, xz_ps%varid(vid), 'actual_range'
                       1
Error: Function ‘nf90_put_att’ at (1) has no IMPLICIT type
m_output.F90:1328:21:

         call nc_chk( nf90_enddef( xz_ps%io ) )
                     1
Error: Function ‘nf90_enddef’ at (1) has no IMPLICIT type
m_output.F90:1329:21:

         call nc_chk( nf90_close( xz_ps%io ) )
                     1
Error: Function ‘nf90_close’ at (1) has no IMPLICIT type
m_output.F90:1336:21:

         call nc_chk( nf90_redef( xz_v%io ) )
                     1
Error: Function ‘nf90_redef’ at (1) has no IMPLICIT type
m_output.F90:1338:23:

           call nc_chk( nf90_put_att( xz_v%io, xz_v%varid(vid), 'actual_range', 
                       1
Error: Function ‘nf90_put_att’ at (1) has no IMPLICIT type
m_output.F90:1340:21:

         call nc_chk( nf90_close( xz_v%io ) )
                     1
Error: Function ‘nf90_close’ at (1) has no IMPLICIT type
m_output.F90:1347:21:

         call nc_chk( nf90_redef( xz_u%io ) )
                     1
Error: Function ‘nf90_redef’ at (1) has no IMPLICIT type
m_output.F90:1349:23:

           call nc_chk( nf90_put_att( xz_u%io, xz_u%varid(vid), 'actual_range', 
                       1
Error: Function ‘nf90_put_att’ at (1) has no IMPLICIT type
m_output.F90:1351:21:

         call nc_chk( nf90_close( xz_u%io ) )
                     1
Error: Function ‘nf90_close’ at (1) has no IMPLICIT type
m_output.F90:903:19:

       call nc_chk( nf90_put_var( hdr%io, hdr%varid(vid), reshape(rbuf,shape(arr
                   1
Error: Function ‘nf90_put_var’ at (1) has no IMPLICIT type
m_output.F90:904:65:

       call nc_chk( nf90_put_var( hdr%io, hdr%vid_t, it*dt, start=(/ it/ntdec_s+
                                                                 1
Error: Keyword argument requires explicit interface for procedure ‘nf90_put_var’ at (1)
m_output.F90:904:19:

       call nc_chk( nf90_put_var( hdr%io, hdr%vid_t, it*dt, start=(/ it/ntdec_s+
                   1
Error: Function ‘nf90_put_var’ at (1) has no IMPLICIT type
m_output.F90:780:17:

     call nc_chk( nf90_def_dim( hdr%io, 'x', nxs, hdr%did_x1 ) )
                 1
Error: Function ‘nf90_def_dim’ at (1) has no IMPLICIT type
m_output.F90:781:17:

     call nc_chk( nf90_def_dim( hdr%io, 'z', nzs, hdr%did_x2 ) )
                 1
Error: Function ‘nf90_def_dim’ at (1) has no IMPLICIT type
m_output.F90:795:19:

       call nc_chk( nf90_put_att( hdr%io, hdr%varid(i), 'long_name', trim(hdr%vn
                   1
Error: Function ‘nf90_put_att’ at (1) has no IMPLICIT type
m_output.F90:796:19:

       call nc_chk( nf90_put_att( hdr%io, hdr%varid(i), 'units', trim(hdr%vunit(
                   1
Error: Function ‘nf90_put_att’ at (1) has no IMPLICIT type
m_output.F90:820:17:

     call nc_chk( nf90_put_att( hdr%io, hdr%vid_x1, 'long_name', 'x' ) )
                 1
Error: Function ‘nf90_put_att’ at (1) has no IMPLICIT type
m_output.F90:821:17:

     call nc_chk( nf90_put_att( hdr%io, hdr%vid_x2, 'long_name', 'z' ) )
                 1
Error: Function ‘nf90_put_att’ at (1) has no IMPLICIT type
m_output.F90:822:17:

     call nc_chk( nf90_put_att( hdr%io, hdr%vid_t, 'long_name', 't' ) )
                 1
Error: Function ‘nf90_put_att’ at (1) has no IMPLICIT type
m_output.F90:823:17:

     call nc_chk( nf90_put_att( hdr%io, hdr%vid_x1, 'units', 'km' ) )
                 1
Error: Function ‘nf90_put_att’ at (1) has no IMPLICIT type
m_output.F90:824:17:

     call nc_chk( nf90_put_att( hdr%io, hdr%vid_x2, 'units', 'km' ) )
                 1
Error: Function ‘nf90_put_att’ at (1) has no IMPLICIT type
m_output.F90:825:17:

     call nc_chk( nf90_put_att( hdr%io, hdr%vid_t, 'units', 's' ) )
                 1
Error: Function ‘nf90_put_att’ at (1) has no IMPLICIT type
m_output.F90:827:17:

     call nc_chk( nf90_put_att( hdr%io, hdr%medid(1), 'long_name', 'rho'    ) )
                 1
Error: Function ‘nf90_put_att’ at (1) has no IMPLICIT type
m_output.F90:828:17:

     call nc_chk( nf90_put_att( hdr%io, hdr%medid(2), 'long_name', 'lambda' ) )
                 1
Error: Function ‘nf90_put_att’ at (1) has no IMPLICIT type
m_output.F90:829:17:

     call nc_chk( nf90_put_att( hdr%io, hdr%medid(3), 'long_name', 'mu'     ) )
                 1
Error: Function ‘nf90_put_att’ at (1) has no IMPLICIT type
m_output.F90:830:17:

     call nc_chk( nf90_put_att( hdr%io, hdr%medid(1), 'units', '10^3 kg/cm^3'   
                 1
Error: Function ‘nf90_put_att’ at (1) has no IMPLICIT type
m_output.F90:831:17:

     call nc_chk( nf90_put_att( hdr%io, hdr%medid(2), 'units', '10^9 Pa' ) )
                 1
Error: Function ‘nf90_put_att’ at (1) has no IMPLICIT type
m_output.F90:832:17:

     call nc_chk( nf90_put_att( hdr%io, hdr%medid(3), 'units', '10^9 Pa'     ) )
                 1
Error: Function ‘nf90_put_att’ at (1) has no IMPLICIT type
m_output.F90:834:17:

     call nc_chk( nf90_put_att( hdr%io, hdr%vid_x1, 'actual_range', (/ xs1(1), x
                 1
Error: Function ‘nf90_put_att’ at (1) has no IMPLICIT type
m_output.F90:835:17:

     call nc_chk( nf90_put_att( hdr%io, hdr%vid_x2, 'actual_range', (/ xs2(1), x
                 1
Error: Function ‘nf90_put_att’ at (1) has no IMPLICIT type
makefile:151: recipe for target 'm_output.o' failed
make: *** [m_output.o] Error 1

**Comment by tktmyd** [comment]
Thank you for the report. This problem happens when one compiles the 2D codes without using NetCDF library. The new release (version 4.1) solves the problem.
