### ISSUE TITLE
There are no clear instructions to compile the source. 

### ISSUE THREAD

**Issue by karimnorouzi** [OpenSWPC/OpenSWPC#9]
I get the following error:

cd swpc_3d;  make arch=
make[1]: Entering directory '/home/karim/models/OpenSWPC/src/swpc_3d'
f77    -o m_pdebug.o 	-c ../shared/m_pdebug.F90
../shared/m_pdebug.F90:19:6:

   use mpi
      1
Fatal Error: Can't open module file ‘mpi.mod’ for reading at (1): No such file or directory
compilation terminated.
makefile:156: recipe for target 'm_pdebug.o' failed
make[1]: *** [m_pdebug.o] Error 1
make[1]: Leaving directory '/home/karim/models/OpenSWPC/src/swpc_3d'
makefile:17: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by tktmyd** [comment]
See
https://tktmyd.github.io/OpenSWPC/English/1._SetUp/1-1_env/
https://tktmyd.github.io/OpenSWPC/English/1._SetUp/1-3_compile/
